export interface GlockitOptions {
    progress?: boolean;
    delay?: number;
    dryRun?: boolean;
    headers?: Record<string, string>;
    platform?: Platform;
}

export interface Platform {
    /** Name of the platform */
    name: string;
    /** Calculate size of object in KB */
    getObjectSizeKB(obj: any): number;
    /** Save results to files */
    saveResults(results: BenchmarkResult, jsonPath?: string, csvPath?: string, htmlPath?: string): Promise<void>;
    /** Log message */
    log(message: string): void;
    /** Log error */
    error(message: string): void;
    /** Read environment variable */
    getEnvVar(name: string): string | undefined;
    /** Get high resolution time in milliseconds */
    now(): number;
    /** Save HTML report */
    saveHtmlReport(htmlContent: string, htmlPath: string): Promise<void>;
}

export interface BenchmarkConfig {
    name?: string;
    endpoints: EndpointConfig[];
    global?: GlobalConfig;
}

export interface GlobalConfig {
    baseUrl?: string;
    maxRequests?: number;
    duration?: number;
    throttle?: number;
    concurrent?: number;
    timeout?: number;
    /**
     * Delay in milliseconds between consecutive requests.
     * This delay is applied after each request, before the next one starts.
     * Default: 0 (no delay)
     */
    requestDelay?: number;
    /**
     * Request scheduling mode.
     * - concurrency: existing worker-loop behavior
     * - arrival-rate: approximate target requests/second control
     */
    executor?: 'concurrency' | 'arrival-rate';
    /**
     * Target requests per second when executor is arrival-rate.
     */
    arrivalRate?: number;
    /**
     * Optional load-shape curve used with arrival-rate execution.
     */
    loadShape?: LoadShapeConfig;
    /**
     * Optional load phases executed in sequence (e.g., warmup, ramp, steady).
     */
    phases?: BenchmarkPhase[];
    /**
     * Optional external dataset for request variable injection.
     */
    dataFeeder?: DataFeederConfig;
    headers?: Record<string, string>;
    /**
     * If true, only summary statistics are kept for each endpoint.
     * requestResults will be empty to save memory.
     */
    summaryOnly?: boolean;
    /**
     * Optional service-level objective thresholds for CI gating.
     */
    slo?: SloConfig;
    /**
     * Optional coordinated omission correction for latency percentiles.
     */
    coordinatedOmission?: CoordinatedOmissionConfig;
    /**
     * Optional weighted multi-scenario traffic mix.
     */
    scenarioMix?: ScenarioMixConfig;
    /**
     * Optional virtual-user session behavior.
     */
    virtualUsers?: VirtualUserConfig;
    /**
     * Optional transaction grouping for user-journey level metrics.
     */
    transactionGroups?: TransactionGroupConfig[];
    /**
     * Optional failure diagnostics with payload masking and sampling.
     */
    diagnostics?: DiagnosticsConfig;
    /**
     * Optional observability exporters.
     */
    observability?: ObservabilityConfig;
    /**
     * Optional output reporters for benchmark artifacts.
     */
    reporters?: ReporterOutputConfig[];
    /**
     * Optional distributed execution mode.
     */
    distributed?: DistributedConfig;
}

export interface DistributedConfig {
    enabled: boolean;
    role: 'coordinator' | 'worker';
    /** Coordinator endpoint used by workers (for example: http://127.0.0.1:9876) */
    coordinatorUrl?: string;
    /** Optional explicit worker id; autogenerated when omitted */
    workerId?: string;
    /** Expected worker count (coordinator mode) */
    expectedWorkers?: number;
    /** Coordinator bind host (coordinator mode) */
    host?: string;
    /** Coordinator bind port (coordinator mode) */
    port?: number;
    /** Time to wait for workers to join */
    joinTimeoutMs?: number;
    /** Time to wait for all worker results */
    resultTimeoutMs?: number;
    /** Worker polling interval while waiting for plan */
    pollIntervalMs?: number;
    /** Worker heartbeat interval while connected to coordinator */
    heartbeatIntervalMs?: number;
    /** Coordinator timeout to consider worker stale */
    staleWorkerTimeoutMs?: number;
    /** Optional shared token required by coordinator APIs */
    authToken?: string;
    /** Header name used for authToken exchange (default: x-glockit-token) */
    authHeaderName?: string;
    /** Number of retries when worker submits final result */
    resultSubmitRetries?: number;
    /** Base backoff in milliseconds for result submission retries */
    resultSubmitBackoffMs?: number;
    /** Number of endpoints leased per plan response (default: 1) */
    leaseBatchSize?: number;
    /** Maximum in-flight leased endpoints allowed per worker */
    maxInFlightLeasedEndpointsPerWorker?: number;
    /** Lease scheduling policy */
    assignmentStrategy?: 'round-robin' | 'least-loaded';
    partitionStrategy?: 'round-robin';
}

export interface DistributedResult {
    role: 'coordinator' | 'worker';
    workerId?: string;
    coordinatorUrl?: string;
    workersTotal?: number;
    workersCompleted?: number;
    staleWorkers?: string[];
    workerCompletedLeaseCounts?: Record<string, number>;
    assignedEndpoints?: string[];
}

export interface ReporterOutputConfig {
    /**
     * Reporter key. Built-ins: json, csv, html, junit.
     */
    type: string;
    /**
     * Optional destination path for the reporter output.
     */
    path?: string;
    /**
     * Reporter-specific options.
     */
    options?: Record<string, any>;
}

export type BenchmarkReporter = (
    result: BenchmarkResult,
    output: ReporterOutputConfig,
    context: {
        platform: Platform;
        generateHtmlReport: () => string;
        generateJunitReport: () => string;
    }
) => Promise<void> | void;

export interface DiagnosticsConfig {
    enabled: boolean;
    /** Maximum number of failure samples to include in summary */
    sampleSize?: number;
    /** Header/body key names to mask (case-insensitive) */
    maskKeys?: string[];
    /** Maximum serialized body length kept in samples */
    maxBodyLength?: number;
    /** Include request/response headers in diagnostic samples */
    includeHeaders?: boolean;
}

export interface DiagnosticSample {
    endpoint: string;
    method: string;
    url: string;
    statusCode?: number;
    error?: string;
    requestHeaders?: Record<string, string>;
    requestBody?: any;
    responseHeaders?: Record<string, string>;
    responseBody?: any;
}

export interface DiagnosticsSummary {
    totalFailures: number;
    sampledFailures: number;
    samples: DiagnosticSample[];
}

export interface TransactionGroupConfig {
    name: string;
    /** Ordered endpoint names included in this transaction group */
    endpoints: string[];
}

export interface TransactionGroupResult {
    name: string;
    endpoints: string[];
    totalRequests: number;
    successfulRequests: number;
    failedRequests: number;
    successRate: number;
    averageResponseTime: number;
    responseTimePercentiles: ResponseTimePercentiles;
    requestsPerSecond: number;
}

export interface VirtualUserConfig {
    /**
     * Isolate variables per concurrent worker/session.
     */
    sessionScope?: boolean;
    /**
     * Persist cookies per session and replay on subsequent requests.
     */
    persistCookies?: boolean;
}

export interface ScenarioMixConfig {
    enabled: boolean;
    /**
     * Scenario selection strategy.
     */
    strategy?: 'weighted-random';
    scenarios: ScenarioDefinition[];
}

export interface ScenarioDefinition {
    name: string;
    /** Relative selection weight; defaults to 1 */
    weight?: number;
    /** Ordered endpoint names representing a user journey */
    flow: string[];
}

export interface CoordinatedOmissionConfig {
    /**
     * Enables latency correction for coordinated omission.
     */
    enabled: boolean;
    /**
     * Expected request interval in milliseconds.
     * If omitted, Glockit tries to derive it from arrivalRate.
     */
    expectedIntervalMs?: number;
}

export interface ObservabilityConfig {
    /**
     * Prometheus exposition endpoint configuration.
     */
    prometheus?: PrometheusExportConfig;
    /**
     * OpenTelemetry OTLP metric export configuration.
     */
    otel?: OTelExportConfig;
}

export interface PrometheusExportConfig {
    enabled: boolean;
    host?: string;
    port?: number;
    path?: string;
    /**
     * If false, the endpoint server is unref'd and will not keep the process alive.
     */
    keepAlive?: boolean;
}

export interface OTelExportConfig {
    enabled: boolean;
    /**
     * OTLP metrics endpoint (for example: http://localhost:4318/v1/metrics).
     */
    endpoint?: string;
    /**
     * Optional HTTP headers sent with OTLP requests.
     */
    headers?: Record<string, string>;
    /**
     * Export interval used by the metric reader.
     */
    intervalMs?: number;
    serviceName?: string;
    attributes?: Record<string, string | number | boolean>;
    /**
     * Optional OTLP traces export configuration.
     */
    traces?: OTelTraceExportConfig;
}

export interface OTelTraceExportConfig {
    enabled: boolean;
    /**
     * OTLP traces endpoint (for example: http://localhost:4318/v1/traces).
     */
    endpoint?: string;
    /**
     * Optional HTTP headers sent with OTLP trace requests.
     */
    headers?: Record<string, string>;
    serviceName?: string;
    attributes?: Record<string, string | number | boolean>;
    /**
     * Probability for span sampling between 0 and 1.
     */
    samplingRatio?: number;
}

export interface ObservabilityResult {
    prometheus?: {
        endpoint: string;
        active: boolean;
    };
    otel?: {
        exported: boolean;
        endpoint?: string;
        error?: string;
    };
    otelTraces?: {
        exported: boolean;
        endpoint?: string;
        error?: string;
    };
    warnings: string[];
}

export interface BenchmarkPhase {
    /** Friendly phase name (e.g., warmup, steady) */
    name: string;
    /** Phase duration in milliseconds */
    duration: number;
    /** Optional concurrent worker override for this phase */
    concurrent?: number;
    /** Optional throttle delay (ms) between requests for this phase */
    throttle?: number;
    /** Optional request delay (ms) for this phase */
    requestDelay?: number;
    /** Optional phase-specific arrival rate (requests per second) */
    arrivalRate?: number;
    /** Optional phase-specific load-shape curve */
    loadShape?: LoadShapeConfig;
}

export interface LoadShapeStep {
    /** Milliseconds from phase/run start where this rate becomes active */
    afterMs: number;
    /** Requests per second from this step onward */
    rate: number;
}

export interface LoadShapeConfig {
    mode: 'step' | 'burst' | 'jitter';
    /** Used when mode=step */
    steps?: LoadShapeStep[];
    /** Used when mode=burst */
    burstIntervalMs?: number;
    /** Used when mode=burst */
    burstDurationMs?: number;
    /** Used when mode=burst */
    burstMultiplier?: number;
    /** Used when mode=jitter; range 0..1 */
    jitterRatio?: number;
}

export interface DataFeederConfig {
    /** Path to JSON or CSV data source */
    path: string;
    /** Source format */
    format: 'json' | 'csv';
    /** Row selection strategy */
    strategy?: 'sequential' | 'random';
}

export interface SloConfig {
    /** Maximum allowed error rate as a decimal (0 to 1) */
    maxErrorRate?: number;
    /** Maximum allowed average response time in milliseconds */
    maxAvgResponseTimeMs?: number;
    /** Maximum allowed p95 response time in milliseconds */
    p95Ms?: number;
    /** Maximum allowed p99 response time in milliseconds */
    p99Ms?: number;
    /** Minimum allowed requests per second */
    minRequestsPerSecond?: number;
}

export interface ResponseTimePercentiles {
    p50: number;
    p90: number;
    p95: number;
    p99: number;
}

export interface SloEvaluation {
    passed: boolean;
    failures: string[];
}

export interface ResponseCheckConfig {
    path: string;
    operator: 'equals' | 'contains' | 'exists' | 'matches';
    value?: any;
}

export type EndpointTransport = 'http' | 'websocket' | 'grpc';

export interface WebSocketEndpointConfig {
    /** Optional explicit message payload; falls back to endpoint.body when omitted. */
    message?: any;
    /** Optional subprotocol for websocket handshake. */
    subprotocol?: string;
    /** Timeout for receiving the first message in milliseconds. */
    responseTimeoutMs?: number;
}

export interface GrpcEndpointConfig {
    /** Path to .proto file used to resolve service and method. */
    protoPath: string;
    /** Optional package scope from the proto document. */
    package?: string;
    /** Fully-qualified gRPC service name, for example: package.Service */
    service: string;
    /** Unary RPC method name. */
    method: string;
    /** Optional request payload for unary calls. */
    payload?: any;
    /** Optional metadata headers for the RPC. */
    metadata?: Record<string, string>;
    /** Use TLS credentials when true; defaults to false (insecure). */
    useTls?: boolean;
}

export interface EndpointConfig {
    name: string;
    url: string;
    method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
    transport?: EndpointTransport;
    headers?: Record<string, string>;
    body?: any;
    maxRequests?: number;
    throttle?: number;
    /**
     * Delay in milliseconds before making this specific request.
     * Overrides the global requestDelay if set.
     * Default: undefined (use global requestDelay)
     */
    requestDelay?: number;
    variables?: VariableExtraction[];
    dependencies?: string[];
    query?: Record<string, string | number | boolean>;
    weight?: number;
    assertions?: AssertionConfig[];
    responseCheck?: ResponseCheckConfig[];
    retries?: number;
    auth?: AuthDependencyConfig;
    /**
     * Use HTTP/2 for the request.
     */
    http2?: boolean;
    /**
     * JavaScript hook to run before the request.
     * Can access: request (config)
     */
    beforeRequest?: string;
    /**
     * JavaScript hook to run after the request.
     * Can access: response (data, status, headers)
     */
    afterRequest?: string;
    /**
     * Optional websocket-specific execution options.
     */
    websocket?: WebSocketEndpointConfig;
    /**
     * Optional gRPC-specific execution options.
     */
    grpc?: GrpcEndpointConfig;
}

export interface AuthDependencyConfig {
    name: string;
    endpoints: EndpointConfig[];
}

export interface VariableExtraction {
    name: string;
    path: string;
    from: 'response' | 'headers' | 'cookies';
}

export interface BenchmarkResult {
    config: BenchmarkConfig;
    results: EndpointResult[];
    summary: BenchmarkSummary;
    timestamp: string;
    htmlPath?: string;
    observability?: ObservabilityResult;
    distributed?: DistributedResult;
}

export interface EndpointResult {
    name: string;
    url: string;
    method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
    totalRequests: number;
    successfulRequests: number;
    failedRequests: number;
    /** Success rate as a value between 0 and 1 */
    successRate: number;
    averageResponseTime: number;
    minResponseTime: number;
    maxResponseTime: number;
    requestsPerSecond: number;
    errors: string[];
    requestResults: RequestResult[];
    totalRequestSizeKB: number;
    averageRequestSizeKB: number;
    totalResponseSizeKB: number;
    averageResponseSizeKB: number;
    responseTimePercentiles: ResponseTimePercentiles;
    phaseResults?: EndpointPhaseResult[];
}

export interface EndpointPhaseResult {
    name: string;
    durationMs: number;
    totalRequests: number;
    successfulRequests: number;
    failedRequests: number;
    requestsPerSecond: number;
}

export interface BenchmarkSummary {
    totalDuration: number;
    totalRequests: number;
    totalSuccessful: number;
    totalFailed: number;
    overallRequestsPerSecond: number;
    averageResponseTime: number;
    responseTimePercentiles: ResponseTimePercentiles;
    errorRate: number;
    coordinatedOmission?: {
        enabled: boolean;
        expectedIntervalMs: number;
        appliedSamples: number;
    };
    transactionGroups?: TransactionGroupResult[];
    diagnostics?: DiagnosticsSummary;
    slo?: SloEvaluation;
}

export interface AssertionConfig {
    path: string;
    operator: 'equals' | 'contains' | 'exists' | 'matches';
    value?: any;
}

export interface RequestResult {
    success: boolean;
    responseTime: number;
    statusCode?: number;
    error?: string;
    data?: any;
    headers?: Record<string, string>;
    requestUrl?: string;
    requestMethod?: string;
    requestHeaders?: Record<string, string>;
    requestBody?: any;
    requestSizeKB?: number;
    responseSizeKB?: number;
    responseCheckPassed?: boolean;
}
